student_controller:
   resource: App\Controller\StudentsController
   type: annotation


app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\SecurityController::register
